### ISSUE TITLE
ntnx-secret.yaml namespace from default to kube-system

### ISSUE THREAD

**Issue by nutanix-nogodan1234** [nutanix/csi-plugin#18]
The ntnx-secret.yaml has namespace info as default but sc.yaml has kube-system for the secret namespace.
```
apiVersion: v1
kind: Secret
metadata:
  name: ntnx-secret
  namespace: default
```
```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
    name: acs-abs
provisioner: com.nutanix.csi
parameters:
    csi.storage.k8s.io/provisioner-secret-name: ntnx-secret
    csi.storage.k8s.io/provisioner-secret-namespace: kube-system
    csi.storage.k8s.io/node-publish-secret-name: ntnx-secret
```
I think we better to present secret template to use kube-system  namespace
