### ISSUE TITLE
@subodh01 Where can I find sample queries? I already installed csi-provisioner-ntnx-plugin `provisioner`, `resizer`.

### ISSUE THREAD

**Issue by h-wookie** [nutanix/csi-plugin#45]
@subodh01 Where can I find sample queries? I already installed csi-provisioner-ntnx-plugin `provisioner`, `resizer`.
I want Nutanix PV usage from prometheus 😥
![image](https://user-images.githubusercontent.com/40632767/150155911-6a292d2f-be7e-4e07-8349-a055c241d275.png)

_Originally posted by @chosam2 in https://github.com/nutanix/csi-plugin/issues/23#issuecomment-1016545988_

**Comment by subodh01** [comment]
You can expose prometheus service on a nodePort and then access csi metrics. Here is an example on how to expose prometheus metrics. You need to modify it to match your prometheus deployment.
```
apiVersion: v1
kind: Service
metadata:
  labels:
    prometheus: k8s
  name: prometheus-k8s
  namespace: ntnx-system
spec:
  ports:
  - name: web
    nodePort: 30900
    port: 9090
    targetPort: web
  selector:
    app: prometheus
    prometheus: k8s
  type: NodePort
```
